version: "3.8"
services:
  app: 
    build:
      context: .
    volumes: 
      - .:/app
    ports: 
      - 7000:3000
    image: app:react-docker-demo
    container_name: react-container
    command: npm start
